### ISSUE TITLE
Screen goes blank

### ISSUE THREAD

**Issue by etricky** [timeseriesadmin/timeseriesadmin#459] opened 2020-08-25 14:21 UTC
Hi

I can replicate this consistently. I start the app, run the query which than shows the result (see below picture).

![image](https://user-images.githubusercontent.com/6766415/91185421-b5c97700-e6e5-11ea-8fba-911df0817fd4.png)

The problem is when I change the Time Format from Timestamp to Date with Seconds where the screen just goes blank. The only way to fix it is to restart the app.

![image](https://user-images.githubusercontent.com/6766415/91185553-e14c6180-e6e5-11ea-913b-b1de0c06570f.png)

This also happens in other scenarios but this one I can replicate every time. I'm running the latest version in Windows 10.

**Comment by jmarceli** [comment] 2020-08-28 19:07
Hi I see that you have `time=0` in your query results this is probably the cause for error. I will let you know when it gets fixed.

**Comment by etricky** [comment] 2020-08-28 21:56
@jmarceli Thank you for your reply. As I mentioned, with this query which shows the total number of records, I can easily replicate the problem but this is also occurring with other queries that do return results so I'm not sure that time=0 is the culprit here. Does the app generate any logs?

**Comment by etricky** [comment] 2020-08-28 22:01
Here's another example of a query where if I change the time format the screen goes blank. The time column is also zero so you are probably correct in your analysis.
![image](https://user-images.githubusercontent.com/6766415/91618326-fba26b80-e981-11ea-9c82-d6d1aebea67f.png)

**Comment by jmarceli** [comment] 2020-08-30 20:31
Please check latest release. Your issue should be fixed now. I have also added a better error reporting. Thanks for reporting that issue.
https://github.com/timeseriesadmin/timeseriesadmin/releases/tag/v0.1.12

**Comment by etricky** [comment] 2020-08-31 08:57
@jmarceli Thank you for providing the new release. My initial tests seem to confirm that the issue is resolved. 

I also want to warn you that in your main page, https://timeseriesadmin.github.io/#download. the download links are pointing to non-existing pages. For example, for Windows, the page has the link https://github.com/timeseriesadmin/timeseriesadmin/releases/download/v.1.12/TimeSeriesAdmin.exe but the available version is v0.1.12 and not v1.12

**Comment by jmarceli** [comment] 2020-08-31 16:21
Thanks for information. Fixed.

**Closed by jmarceli** 2020-08-31 16:21 UTC
Labels: bug
